### ISSUE TITLE
Port number specification is ignored

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs_control#1]
The port number specification in `riak_cs_control.app.src` and reference by the README is overridden by the specification of `{port, 8000}` in `riak_cs_control_sup`.

**Comment by kellymclaughlin** [comment]
Maybe I'm misunderstanding. It looks like the port in the app.src file is the port CS is listening on and port 8000 is for cs_control to listen on. Is that right? May be just the README is not quite right.

**Comment by cmeiklejohn** [comment]
[bcef589] I clarified those optiosn in the README, but those are intended as just the Riak CS configuration.  Should I make it a nested proplist?

**Comment by cmeiklejohn** [comment]
I think we're all good here.
