### ISSUE TITLE
Webmachine resource module naming

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs_control#3]
The general convention for wm resource module names would be more like `riak_cs_control_wm_users` instead of `riak_cs_control_users_resource`. No big deal, but it is a few less characters and would keep things consistent with other projects.

**Comment by cmeiklejohn** [comment]
Renamed 3 resources in [8847f8a].

**Comment by cmeiklejohn** [comment]
Oops, [da67722].
